[build]
  base = "Front-End"
  publish = "dist/front-end"  # Cambia questa linea per corrispondere all'outputPath
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
