[build]
  command = "npm install --force && npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"

[context.deploy-preview]
  command = "npm install --force && npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm install --force && npm run build"
  publish = "dist"
